apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-web
        image: ecommerce-app:v1 # In a real scenario, this would be pushed to DockerHub
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
